apiVersion: v1
kind: PersistentVolume

metadata:
  name: video-dataset-pv

spec:
  capacity:
    storage: 10Gi
  
  accessModes:
  - ReadOnlyMany

  storageClassName: ""

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /home/baturalp/datasets
    # change this path with respect to your own dataset path