apiVersion: v1
kind: PersistenVolumeClaim

metadata:
  name: video-dataset
  namespace: video-pipeline

spec:
  accessModes:
    - ReadOnlyMany

  resources:
    requests:
      storage: 10Gi
  
  volumeName: video-dataset-pv
  