apiVersion: v1
kind: PersistenVolume

metadata:
  name: video-dataset-pv

spec:
  capacity:
    storage: 1Gi
  
  accessModes:
  - ReadOnlyMany

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /home/baturalp/datasets
    # change this path with respect to your own dataset path