apiVersion: v1
kind: PersistenVolumeClaim

metadata:
  name: video_dataset
  namespace: video_pipeline

spec:
  accessModes:
    - ReadOnlyMany

  resources:
    requests:
      storage: 10Gi
  
  volumeName: video-dataset-pv
  