apiVersion: v1
kind: Service

metadata:
  name: superset-db
  namespace: video-pipeline

spec:
  clusterIP: None

  selector:
    app: superset-db

  ports:

  - name: postgres
    port: 5432
    targetPort: postgres
